version: "1.0"
info:
  model: int-scaffold
packages:
- name: AVIVS_POALIM_PROJECT_1Project
  gitServerName: https://github.com/AvivSimDS/
  gitUrl: https://github.com/AvivSimDS/AVIVS_POALIM_PROJECT_1Project
  gitUsername: AvivSimDS
  gitBranch: main
services:
- serviceName: project.avivs_poalim_project_1.integrations:SampleFlowService2DB_1
  packages:
  - name: AVIVS_POALIM_PROJECT_1Project
    version: "1.0"
